### ISSUE TITLE
Web pack and fonts

### ISSUE THREAD

**Issue by emilyb7** [CYPIAPT-LNDSE/goals-app#105]
I'm having trouble using our font LeagueSpartan-Bold with the current webpack / sass setup. It's causing weird errors.

Using a boring font in the meantime.

**Comment by emilyb7** [comment]
Nori sent me this example:

SASS: `@font-face { font-family: Rosie; src: url('../../public/fonts/Rosie/rosie-regular-webfont.woff2'); }` 

webpack config : 
``` 
  {
          test: /\.(eot|svg|ttf|otf|woff|woff2)$/,
          loader: 'file-loader?name=public/fonts/[name].[ext]'
      }
```

**Comment by MHemsley** [comment]
Did that work?


On 8 Mar 2017, at 13:20, Emily Bertwistle <notifications@github.com> wrote:


Nori sent me this example:
SASS: @font-face { font-family: Rosie; src: url('../../public/fonts/Rosie/rosie-regular-webfont.woff2'); }
webpack config :
  {
          test: /\.(eot|svg|ttf|otf|woff|woff2)$/,
          loader: 'file-loader?name=public/fonts/[name].[ext]'
      }

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, 
view it on GitHub, or 
mute the thread.







{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/CYPIAPT-LNDSE/goals-app","title":"CYPIAPT-LNDSE/goals-app","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png" class="">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png" class="">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/CYPIAPT-LNDSE/goals-app" class="">https://github.com/CYPIAPT-LNDSE/goals-app</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@emilyb7 in #105: Nori sent me this example:\r\n\r\nSASS: `@font-face { font-family: Rosie; src: url('../../public/fonts/Rosie/rosie-regular-webfont.woff2'); }` \r\n\r\nwebpack config : \r\n``` \r\n  {\r\n          test: /\\.(eot|svg|ttf|otf|woff|woff2)$/,\r\n          loader: 'file-loader?name=public/fonts/[name].[ext]'\r\n      }\r\n```"}],"action":{"name":"View Issue","url":"<a href="https://github.com/CYPIAPT-LNDSE/goals-app/issues/105#issuecomment-285038254" class="">https://github.com/CYPIAPT-LNDSE/goals-app/issues/105#issuecomment-285038254</a>"}}}




  This email has been scanned for email related threats and delivered safely by Mimecast. For more information please visit http://www.mimecast.com

**Comment by emilyb7** [comment]
@MHemsley i haven't tried it yet!

**Comment by emilyb7** [comment]
fixed :)
