### ISSUE TITLE
Oauth flow

### ISSUE THREAD

**Issue by shiryz** [CYPIAPT-LNDSE/goals-app#187]

**Comment by emilyb7** [comment]
We can set up the login manually:

https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow

Or use the JavaScript SDK which is client-side:

https://developers.facebook.com/docs/facebook-login/web/permissions

**Comment by MHemsley** [comment]
Would there be any benefit to setting up this manually? The SDK is pretty easy to use


On 28 Mar 2017, at 13:23, Emily Bertwistle <notifications@github.com> wrote:


We can set up the login manually:
https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow
Or use the JavaScript SDK which is client-side:
https://developers.facebook.com/docs/facebook-login/web/permissions
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, 
view it on GitHub, or 
mute the thread.







{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/CYPIAPT-LNDSE/goals-app","title":"CYPIAPT-LNDSE/goals-app","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png" class="">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png" class="">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/CYPIAPT-LNDSE/goals-app" class="">https://github.com/CYPIAPT-LNDSE/goals-app</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@emilyb7 in #187: We can set up the login manually:\r\n\r\<a href="nhttps://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow\r\n\r\nOr" class="">nhttps://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow\r\n\r\nOr</a> use the JavaScript SDK which is client-side:\r\n\r\<a href="nhttps://developers.facebook.com/docs/facebook-login/web/permissions\r\n\r\n" class="">nhttps://developers.facebook.com/docs/facebook-login/web/permissions\r\n\r\n</a>"}],"action":{"name":"View Issue","url":"<a href="https://github.com/CYPIAPT-LNDSE/goals-app/issues/187#issuecomment-289752602" class="">https://github.com/CYPIAPT-LNDSE/goals-app/issues/187#issuecomment-289752602</a>"}}}




  This email has been scanned for email related threats and delivered safely by Mimecast. For more information please visit http://www.mimecast.com

**Comment by emilyb7** [comment]
@MHemsley since we've not worked with FB before, we were going to look into both and see which is easier, but if you think the SDK is the better option then I think we're happy to go with that!

**Comment by MHemsley** [comment]
Personal opinion, I would definitely recommend that you research and check what you feel more comfortable with


On 28 Mar 2017, at 14:45, Emily Bertwistle <notifications@github.com> wrote:


@MHemsley since we've not worked with FB before, we were going to look into both and see which is easier, but if you think the SDK is the better option then I think we're happy to go
 with that!
—
You are receiving this because you were mentioned.
Reply to this email directly, 
view it on GitHub, or 
mute the thread.







{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/CYPIAPT-LNDSE/goals-app","title":"CYPIAPT-LNDSE/goals-app","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png" class="">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png" class="">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/CYPIAPT-LNDSE/goals-app" class="">https://github.com/CYPIAPT-LNDSE/goals-app</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@emilyb7 in #187: @MHemsley since we've not worked with FB before, we were going to look into both and see which is easier, but if you think the SDK is the better option then I think we're happy to go with that!"}],"action":{"name":"View Issue","url":"<a href="https://github.com/CYPIAPT-LNDSE/goals-app/issues/187#issuecomment-289774424" class="">https://github.com/CYPIAPT-LNDSE/goals-app/issues/187#issuecomment-289774424</a>"}}}</sc
 ript>




  This email has been scanned for email related threats and delivered safely by Mimecast. For more information please visit http://www.mimecast.com

**Comment by shiryz** [comment]
Closing, oauth has been implemented.
