### ISSUE TITLE
Where to deploy to

### ISSUE THREAD

**Issue by emilyb7** [CYPIAPT-LNDSE/goals-app#264]
Hi @MHemsley, 

You mentioned in an issue some time ago that you want to deploy to AWS eventually.

I just want to check, is this something that you expect us to take care of? Or is this more of a long-term goal on your side?

At the moment we are working with Heroku. However, this definitely isn't a viable solution for the long-term because it's causing issues with Facebook (something like what's described here... http://stackoverflow.com/questions/16086615/5-unauthorized-source-ip-address-error-on-heroku-rails-app).

**Comment by MHemsley** [comment]
I think our preference is generally AWS because of these kinds of issues, and it's higher flexibility/scalability of the architecture side of things.

Have you deployed to AWS before/is it of interest learning for you? If not, I can take care of it, just not entirely sure of when I will have capacity this week. 

How baked in is the FB integration, as it might be worth using AWS cognito to handle the ID side of things?

**Comment by emilyb7** [comment]
@MHemsley neither of us have deployed to AWS before and we have quite a lot of other stuff to get finished this week, so it might be best if you take care of that side of things!
