### ISSUE TITLE
Receive DB data overwriting existing goals if network connection lost

### ISSUE THREAD

**Issue by emilyb7** [CYPIAPT-LNDSE/goals-app#268]
Version on https://polar-dawn-55555.herokuapp.com/ currently includes #263 

If network connection is lost, 'RECEIVE_DB_DATA' action is triggered on reconnection. This causes all goals in the state to be replaced. So goals that were created while network connection is down are lost.

To fix: trigger RECEIVE_DB_DATA in redux only if it's a new connection.

**Comment by emilyb7** [comment]
Idea to fix: RECEIVE_DB_DATA to run only if `state.goals.length === 0`

**Comment by MHemsley** [comment]
Hi both,


that seems to be a fix to me. Just in general, it would be helpful if you could log things that would be done if this was a PWA (so that any future sprint planning is made easier). 


On 24 Apr 2017, at 16:55, Emily Bertwistle <notifications@github.com> wrote:


Idea to fix: RECEIVE_DB_DATA to run only if state.goals.length === 0
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, 
view it on GitHub, or 
mute the thread.







{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/CYPIAPT-LNDSE/goals-app","title":"CYPIAPT-LNDSE/goals-app","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png" class="">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png" class="">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/CYPIAPT-LNDSE/goals-app" class="">https://github.com/CYPIAPT-LNDSE/goals-app</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@emilyb7 in #268: Idea to fix: RECEIVE_DB_DATA to run only if `state.goals.length === 0`"}],"action":{"name":"View Issue","url":"<a href="https://github.com/CYPIAPT-LNDSE/goals-app/issues/268#issuecomment-296717139" class="">https://github.com/CYPIAPT-LNDSE/goals-app/issues/268#issuecomment-296717139</a>"}}}





  This email has been scanned for email related threats and delivered safely by Mimecast. For more information please visit http://www.mimecast.com

**Comment by emilyb7** [comment]
fixed with #250
