### ISSUE TITLE
Add to README

### ISSUE THREAD

**Issue by MHemsley** [CYPIAPT-LNDSE/goals-app#60]
As per my 'announcement' last night. Could you add the current tech stack, technologies needed for MVP (e.g. database, static page framework), and any architectural considerations needed for the MVP (e.g. how is patient information needed, how to manage accounts)

**Comment by emilyb7** [comment]
@shiryz we maybe need to talk to other people about this, but here are my thoughts:

- hapi server
- postgres database for storing user data
- user login, either conventional username + password, or [passwordless](https://medium.freecodecamp.com/360-million-reasons-to-destroy-all-passwords-9a100b2b5001#.9tj6u0noz), or Facebook oAuth
- if we have user login, we probably also need a simple mail server
- if we go with the passwordless approach, we def need a mail server
- React and redux on the frontend (yes, we can do it!)

We don't need patient data, we won't store actual names or passwords. Only email addresses. Users are free to remain anonymous.

**Comment by MHemsley** [comment]
Hi @emilyb7,

Can I check the rationale behind using React/Redux?

M

**Comment by emilyb7** [comment]
Hi @MHemsley 

Frankly, my own biggest motivation for using React is that I have recently learnt a bit and would like the chance to implement it on a slightly bigger project.

If you have a good reasons not to use it, then I would absolutely be willing to reconsider.

My (unqualified) opinion on why it might be useful is:
- it would enable us to have a one-page site with app-like functionality (instead of the massive html file that we have now, or just static pages from the server)
- we could load all user data (i.e. goals, progress) into the state (would make switching between steps very fast?)
- use the state to manage which step of the user journey the user is on
- nice way of creating a kind of template without relying on the server

But maybe there is a better way of doing all this. I would hoping to get some advice from more experienced people at FAC.

For testing we have used Tape. For CI, Travis. I think that part is relatively certain (unless @shiryz has other ideas?), so will put it into the readme too.
