### ISSUE TITLE
Presentation for pitch

### ISSUE THREAD

**Issue by amgoforth** [CYPIAPT-LNDSE/goals-app#65]
@emilyb7 @shiryz I've put together a draft deck of slides for tomorrow - uploaded to resources.  It needs work - I will add stuff on evidence base, and user experience.  If you have any thoughts on implementation and technical viability that would be cool, and your thoughts on the roadmap, also cool.  If you can't add stuff here, or to the slides, we can add before the pitch tomorrow evening.  I'll be around AFC from 5pm.
See you tomorrow.

**Comment by emilyb7** [comment]
@amgoforth 

the product road map looks ok so far. Here are some things I think would be worth mentioning. I think it would also be wise to prioritise a bit, so point out what is essential and what we will aim to do but may drop off if we encounter difficulties.

Things not on the list include:
- user can log in and out (how? username and password?)
- accessibility (how far do we go with this?)
- browser compatibility (ditto, this takes a lot of time)
- login for the clinician? generating a report for a clinician? (not saying this is needed, it's just something we mentioned at the beginning of the project)
- mail server, email notifications when a user signs up to the platform (shouldn't be too technically challenging, but it is a consideration)

**Comment by emilyb7** [comment]
In case you want to add some branding to the presentation, you can find all our icons here :) https://github.com/CYPIAPT-LNDSE/goals-app/tree/master/public/icons

**Comment by emilyb7** [comment]
@amgoforth I think implementation is more your area of expertise.

For evidence, I think we can make the arguments stronger with real examples! (doesn't need to be on the slides as such, just something you can explain)

For product ownership, explain the expertise *you* have in this area.

For technical viability, the project can be broken down into smaller parts. This is closely linked to the product roadmap. We need to know which bits are priorities. We can make a more compelling case if we are realistic about which bits we need, and which bits are just nice to have. It is an MVP after all, so everything that is not essential should be moved down the list of priorities.

And there needs to be a trade off between the functionality and the aesthetics (think of breathe with me, it doesn't *do* an awful lot (it doesn't store data, for instance), but it is very beautiful. We may not be able to get ours that beautiful, as we want to do more things!)

Once broken down into smaller parts, the individual bits of the project are not particularly challenging. There's nothing in there that @shiryz and I can't already do, so that is not a problem at all. But it is definitely a lot to get through in 4 weeks!

**Comment by emilyb7** [comment]
@amgoforth we'll aim to be at anna freud centre by 5pm, or soon after, so we can go over this before the pitch. See you later :)

**Comment by bradreeder** [comment]
Closed. Presentation was good - project got selected, much win. :-)
