### ISSUE TITLE
Resources for learning React

### ISSUE THREAD

**Issue by emilyb7** [CYPIAPT-LNDSE/goals-app#70]
Here's some stuff I have used.

This was the first tutorial I did. I didn't particularly love it, but the first two sections (before starting on redux) are enough to get used to the basics (FAC have bought this from udemy so it's free):
https://www.udemy.com/react-redux/

Justgiving guy Pete's tutorial, this also includes some testing resources and it explains the setup in lots of detail, really useful!
https://github.com/peterthompson/workshop-fundraiser-leaderboard

Alternative guide to setup, I was using this one before Pete's talk:
https://www.tutorialspoint.com/reactjs/reactjs_environment_setup.htm

Also lots of info here which I found useful when I first started learning:
https://www.quora.com/Whats-the-best-place-to-learn-React-js

**Comment by MHemsley** [comment]
I've got access to safari (online book library for tech subjects), I can lend log in if helpful. The code academy tutorial is basic, but good for core principles.




Get Outlook for Android





On Thu, Mar 2, 2017 at 3:11 PM +0000, "Emily Bertwistle"
<notifications@github.com> wrote:



Here's some stuff I have used.
This was the first tutorial I did. I didn't particularly love it, but the first two sections (before starting on redux) are enough to get used to the basics (FAC have bought this from udemy so it's free):
https://www.udemy.com/react-redux/
Justgiving guy Pete's tutorial, this also includes some testing resources and it explains the setup in lots of detail, really useful!
https://github.com/peterthompson/workshop-fundraiser-leaderboard
Alternative guide to setup, I was using this one before Pete's talk:
https://www.tutorialspoint.com/reactjs/reactjs_environment_setup.htm
Also lots of info here which I found useful when I first started learning:
https://www.quora.com/Whats-the-best-place-to-learn-React-js
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, 
view it on GitHub, or 
mute the thread.






{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/CYPIAPT-LNDSE/goals-app","title":"CYPIAPT-LNDSE/goals-app","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/CYPIAPT-LNDSE/goals-app"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Resources for learning React (#70)"}],"action":{"name":"View Issue","url":"https://github.com/CYPIAPT-LNDSE/goals-app/issues/70"}}}



  This email has been scanned for email related threats and delivered safely by Mimecast. For more information please visit http://www.mimecast.com
